//! .sc file writer: emits Sound Cabinet pattern definitions from resolved notes.

use super::resolver::ResolvedNote;
use super::theory::PitchClass;

/// Write all variations as .sc pattern definitions.
pub fn write_sc(
    variations: &[Vec<ResolvedNote>],
    voice_name: &str,
    pattern_name: &str,
    key_name: &str,
    mode_name: &str,
    chord_names: &str,
    key_root: PitchClass,
    total_beats: f64,
) -> String {
    let mut out = String::new();

    out.push_str(&format!(
        "// Generated by: {} + {} {} + [{}]\n\n",
        pattern_name, key_name, mode_name, chord_names
    ));

    for (i, notes) in variations.iter().enumerate() {
        let letter = variation_letter(i);
        let var_name = format!("{}_{}", voice_name, letter);

        out.push_str(&format!(
            "pattern {} = {} beats\n",
            var_name,
            format_beats(total_beats)
        ));

        for note in notes {
            if note.is_rest {
                continue; // rests are implicit (absence of sound)
            }

            let note_name = note.pitch.to_note_name(Some(key_root));
            let beat_str = format_beats(note.beat_offset);
            let dur_str = format_beats(note.duration_beats);

            // Include velocity as gain multiplier if not 1.0
            if (note.velocity - 1.0).abs() < 0.01 {
                out.push_str(&format!(
                    "  at {beat_str} play {voice_name}({note_name}) for {dur_str} beats\n"
                ));
            } else {
                out.push_str(&format!(
                    "  at {beat_str} play {voice_name}({note_name}) * {vel} for {dur_str} beats\n",
                    vel = format_velocity(note.velocity)
                ));
            }
        }

        out.push('\n');
    }

    out
}

/// Format a beat value cleanly (public for song.rs).
pub fn format_beats_pub(beats: f64) -> String {
    format_beats(beats)
}

/// Format velocity (public for song.rs).
pub fn format_velocity_pub(v: f64) -> String {
    format_velocity(v)
}

/// Variation letter (public for song.rs).
pub fn variation_letter_pub(index: usize) -> String {
    variation_letter(index)
}

/// Format a beat value cleanly: integers without decimal, fractions with minimal digits.
fn format_beats(beats: f64) -> String {
    if (beats - beats.round()).abs() < 1e-10 {
        format!("{}", beats.round() as i64)
    } else if (beats * 4.0 - (beats * 4.0).round()).abs() < 1e-10 {
        // Clean quarter-beat fractions: 0.25, 0.5, 0.75
        format!("{:.2}", beats)
            .trim_end_matches('0')
            .trim_end_matches('.')
            .to_string()
    } else {
        format!("{:.3}", beats)
            .trim_end_matches('0')
            .trim_end_matches('.')
            .to_string()
    }
}

/// Format velocity (0.0-1.0) as a clean decimal.
fn format_velocity(v: f64) -> String {
    if (v * 10.0 - (v * 10.0).round()).abs() < 1e-10 {
        format!("{:.1}", v)
    } else {
        format!("{:.2}", v)
    }
}

/// Map variation index to letter: 0->a, 1->b, ..., 25->z, 26->aa, etc.
fn variation_letter(index: usize) -> String {
    if index < 26 {
        String::from((b'a' + index as u8) as char)
    } else {
        let first = (b'a' + (index / 26 - 1) as u8) as char;
        let second = (b'a' + (index % 26) as u8) as char;
        format!("{first}{second}")
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::generate::theory::Pitch;

    #[test]
    fn test_format_beats() {
        assert_eq!(format_beats(0.0), "0");
        assert_eq!(format_beats(1.0), "1");
        assert_eq!(format_beats(0.5), "0.5");
        assert_eq!(format_beats(0.25), "0.25");
        assert_eq!(format_beats(0.75), "0.75");
        assert_eq!(format_beats(2.0), "2");
    }

    #[test]
    fn test_variation_letter() {
        assert_eq!(variation_letter(0), "a");
        assert_eq!(variation_letter(1), "b");
        assert_eq!(variation_letter(25), "z");
        assert_eq!(variation_letter(26), "aa");
    }

    #[test]
    fn test_write_sc_basic() {
        let notes = vec![
            ResolvedNote {
                beat_offset: 0.0,
                pitch: Pitch::from_note_name("D2").unwrap(),
                duration_beats: 1.0,
                velocity: 1.0,
                is_rest: false,
            },
            ResolvedNote {
                beat_offset: 1.0,
                pitch: Pitch::from_note_name("E2").unwrap(),
                duration_beats: 1.0,
                velocity: 0.4,
                is_rest: false,
            },
        ];

        let output = write_sc(
            &[notes],
            "bass",
            "walking-jazz",
            "D",
            "dorian",
            "Dm7",
            PitchClass::D,
            4.0,
        );

        assert!(output.contains("pattern bass_a = 4 beats"));
        assert!(output.contains("at 0 play bass(D2) for 1 beats"));
        assert!(output.contains("at 1 play bass(E2) * 0.4 for 1 beats"));
    }

    #[test]
    fn test_rests_omitted() {
        let notes = vec![
            ResolvedNote {
                beat_offset: 0.0,
                pitch: Pitch::from_note_name("C3").unwrap(),
                duration_beats: 1.0,
                velocity: 1.0,
                is_rest: false,
            },
            ResolvedNote {
                beat_offset: 1.0,
                pitch: Pitch::from_midi(60),
                duration_beats: 1.0,
                velocity: 0.7,
                is_rest: true,
            },
        ];

        let output = write_sc(
            &[notes],
            "bass",
            "test",
            "C",
            "major",
            "Cmaj",
            PitchClass::C,
            4.0,
        );

        // Should only have one "at" line (the rest is omitted)
        let at_count = output.matches("at ").count();
        assert_eq!(at_count, 1);
    }
}
